In [0]:
import pandas as pd
df = pd.DataFrame([[18,10,5,11,-2],
                    [2,-2,9,-11,3],
                    [-4,6,-19,2,1],
                    [3,-14,1,-2,8],
                    [-2,2,4,6,13]],
                  index = list('pqrst'),
                    columns = list('abcde'))

In [0]:
import numpy as np

In [0]:
new_df = pd.DataFrame(df[df.apply(np.sum, axis = 1) % 2 == 0])

In [19]:
new_df

    a   b   c   d  e
p  18  10   5  11 -2
r  -4   6 -19   2  1
s   3 -14   1  -2  8

In [0]:
new_df.to_excel('file_df.xlsx', sheet_name = 'Sheet1')

In [0]:
df_temp = new_df

In [34]:
df_temp

    a   b   c   d  e
p  18  10   5  11 -2
r  -4   6 -19   2  1
s   3 -14   1  -2  8

In [0]:
df_temp.eval('m = (a*b*c*d*e)', inplace=True)

In [43]:
df_temp

    a   b   c   d  e      m
p  18  10   5  11 -2 -19800
r  -4   6 -19   2  1    912
s   3 -14   1  -2  8    672

In [0]:
writer = pd.ExcelWriter('file_df.xlsx')
df_temp.to_excel(writer, sheet_name='Sheet2')
writer.save()
writer.close()

In [46]:
pd.read_excel('file_df.xlsx', sheet_name='Sheet2')

  Unnamed: 0   a   b   c   d  e      m
0          p  18  10   5  11 -2 -19800
1          r  -4   6 -19   2  1    912
2          s   3 -14   1  -2  8    672